name: pr-unit-tests
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: pgsql, pdo_pgsql
      - name: Uping database container
        run: docker run --name database -e POSTGRES_USER=test -e POSTGRES_DB=test -e POSTGRES_PASSWORD=test -p 5471:5432 -d -h 0.0.0.0 postgres:13.3 -c log_statement=all
      - name: Waiting to database container be ready
        run: sleep 5

      - name: Installing dependencies
        run: composer install --ignore-platform-reqs --optimize-autoloader

      - name: Creating .env file..
        run: cp .env.example .env
      - name: Criando/populando tabelas banco para testes
        run: php artisan migrate --path="database/migrations/" --seed

      - name: Iniciando testes..
        run: php artisan test
